### ISSUE TITLE
Can not update when already installed 

### ISSUE THREAD

**Issue by dsteinberger** [gantsign/ansible-role-postman#21]
I can't update postman to a new version...

Because : https://github.com/gantsign/ansible-role-postman/blob/master/tasks/main.yml#L74
Doc: Creates: A filename, when it already exists, this step will not be run.

I try to remove Creates and its working 
But we need to add step before install Postman to create a directory, I think

**Comment by freemanjp** [comment]
@dsteinberger sorry for taking so long to get to this, you can find an enhancement resolving the issue you reported in version [2.1.0](https://github.com/gantsign/ansible-role-postman/releases/tag/2.1.0).
